apiVersion: v1
kind: Service
metadata:
  name: admin-dashboard-blue
  namespace: platform-services
spec:
  selector:
    app: admin-dashboard
    version: blue
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
